version: '2.2'
services:
  
  member1:
    image: member1
    ports:
      - 127.0.0.1:4001:4001
    environment:
      - DEBUG_PORT=4001
    networks: 
      - source-network

  member2:
    image: member2
    ports:
      - 127.0.0.1:4002:4002
    environment:
      - DEBUG_PORT=4002
    networks:
      - source-network
      - cloud-network
  
  member3:
    image: member3
    ports:
      - 127.0.0.1:4003:4003
    environment:
      - DEBUG_PORT=4003
    networks: 
      - cloud-network    
      
networks:
  source-network:
    external: true
  cloud-network:
    external: true

### create networks before the start    
# docker network create --driver=bridge -o "com.docker.network.bridge.enable_ip_masquerade"="false" --subnet=192.168.1.0/24 --gateway=192.168.1.1 source-network
# docker network create --driver=bridge -o "com.docker.network.bridge.enable_ip_masquerade"="false" --subnet=192.168.2.0/24 --gateway=192.168.2.1 cloud-network

# docker-compose -f docker-compose.yml up